### ISSUE TITLE
Credentials resolution

### ISSUE THREAD

**Issue by pgrzesik** [serverless/compose#11]
**Problem** 

At the moment, Framework has multiple issues with credentials resolution (https://github.com/serverless/serverless/issues/9290). For the `components`, in the long run, we would like to support cases where components that are part of the same service, can be deployed using different credential sets.

**Current situation**

Credentials are resolved as a part of processing inside `Serverless` class instance, they do not strictly follow resolution order that AWS SDK does by default.

**Subprocess approach**

In the `subprocess` approach, the credentials are local to a single subprocess. However, the only supported options to actually use different credential sets is using `provider.profile` setting or using credentials provided from Dashboard integration. The reason for that is the fact that at the moment, we don't have a mechanism that allows mapping multiple values of `AWS_*` env variables separately for each process. In order to support passing different set of credentials for separate components via env vars, we would have to support mapping from custom env variables to `AWS_ACCESS_KEY_ID` and so on for each component. This obviously isn't ideal as it requires the user to use some custom mapping logic 

**Programmagic approach**

In the `programmatic` approach, the credentials are local to a single `Serverless` class instance that would be created for each separate component. As the environment variables are shared, the only supported options to actually use different credential sets is using `provider.profile` setting or using credentials provided from Dashboard integration, similarily to `subprocess` approach. Here, however, we don't have a clear way of potentially implementing a support for environment variables mapping, similar to `subprocess`, because the env vars are shared. That would require us to resort to still relying on the custom credentials resolution mechanism.

**Potential solution (high level)**

1. Implement `credential provider` (name to be adjusted) at the `components` level and pass the resolved credentials directly to each component (either programmatically or e.g. as env vars with `subprocess` approach). The downside of this approach is the fact that we will still be relying on custom credential resolution logic that has been problematic this far (see the linked issue at the beginning). 
2. Keep the credentials resolution logic internal as it is at the moment and do not support deployment with different set of credentials for different components unless `provider.profile` or Dashboard integration is used. 
3. ?

**Notes**

The property `provider.profile` has been considered to be removed for a long time, so relying on it might not be the best idea.

**Comment by mnapoli** [comment]
I'll close this issue since it stems from the very beginning, and right now all credential resolution happens in each `serverless` sub-process.
