### ISSUE TITLE
"Serverless Components CLI is no longer bundled with Serverless Framework CLI" when deploying

### ISSUE THREAD

**Issue by RobertGoacher** [serverless/compose#115]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

When I try to run `serverless deploy` or `serverless info` I get an error when it reaches any of the services which are using a Serverless Component.

The full error I receive is:

```
api › Running "serverless deploy --stage dev"
api › Serverless Components CLI is no longer bundled with Serverless Framework CLI
api › 
api › To run it, ensure it's installed:
api › npm install -g @serverless/components
api › 
api › Then run:
api › components <command> <options>
```

Here is the contents of my serverless-compose.yml file:

```
services:
  databases:
    path: databases

  api:
    path: api

```

The 'api' service is using the `express` component (https://github.com/serverless-components/express).

The api service works perfectly when I manually run `serverless deploy` within its directory.

### Service configuration (serverless-compose.yml) content

```yaml
services:
  databases:
    path: databases

  api:
    path: api
```

### Command name and used flags

serverless info

### Command output

```shell
api › Serverless Components CLI is no longer bundled with Serverless Framework CLI
api › 
api › To run it, ensure it's installed:
api › npm install -g @serverless/components
api › 
api › Then run:
api › components <command> <options>
api ›
```

**Comment by pgrzesik** [comment]
Hello @RobertGoacher - this repository is not related to components. As for the issue you're having - the message suggests what the solution is, since V3 release of the Serverless Framework, components are no longer bundled with it. You need to install them separately and run as suggested in the command output message.

I'm going to close this issue.

**Comment by pgrzesik** [comment]
Sorry about that @RobertGoacher - the Compose is mentioned in Framework docs only, but we'll see if we can improve the messaging a little bit so we can avoid situations like this.
