### ISSUE TITLE
Add `--max-concurrency` CLI flag to limit the number of deployments happening in parallel

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#134]
For apps with a lot of services, deploying 10 or 20 services in parallel will not always work (rate limits, overloading the system, network, etc.).

The idea here is to introduce a new CLI flag (for example `--max-concurrency=5`) that limits the number of deployments (or any other command) running in parallel.

By default (without the option), there would be no changes on concurrency.

**Comment by pgrzesik** [comment]
Hey @kopertop - it will be out with the next compose release, most likely later today 👍
