### ISSUE TITLE
Cannot resolve serverless.yml: "service" property is not accessible

### ISSUE THREAD

**Issue by gkuga** [serverless/compose#155]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

We want to pass a value from a parameter in serverless-compose.yml to the service property in serverless.yml. It looks like the following

```yaml
# serverless-compose.yml
services:
  Foo:
    path: bar
    params:
      BazParam: 'baz-val' # This is fixed value
```

```yaml
# service.yaml
service: ${param:BazParam}
```

But we run into this error.

```sh
Cannot resolve serverless.yml: "service" property is not accessible (configured behind variables which cannot be resolved at this stage)
```

Since it is a fixed value passed from serverless-compose.yml, it seems to me that it should be resolved first.

### Service configuration (serverless-compose.yml) content

```yaml
N/A
```

### Command name and used flags

sls Foo:print or sls deploy

### Command output

```shell
sls Foo:print
Running "serverless" from node_modules
Running "serverless" from node_modules
Environment: darwin, node 16.16.0, framework 3.22.0 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: "service" property is not accessible (configured behind variables which cannot be resolved at this stage)
Error: 



Verbose logs are available in ".serverless/compose.log"
```

**Comment by gkuga** [comment]
Thanks for your reply. I will deal with this in a different way.

**Comment by azelezni** [comment]
Can we please get more information regarding this?
Why exactly is it not possible to use variables in the `service:` key?
What is the reasoning behind this?

**Comment by chrisdugne** [comment]
As a workaround, I use a script to export an environment variable, and this can be used for `service`.
Removing all my other config stuff this is what I use:

.sh:
```sh
export SERVICE=xxx
serverless deploy .....
```

serverless.yml:
```yml
service: ${env:SERVICE}
```
