### ISSUE TITLE
Request network error: FetchError: request to https://service-xxxxxx-xxxxxx.gz.apigw.tencentcs.com/release/ failed

### ISSUE THREAD

**Issue by mefengl** [serverless/compose#168]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

it will show an error that indicates a failed call to https://....tencentcs.com/release, I don't know why it need to call Tencent.
I have already set `export SERVERLESS_PLATFORM_VENDOR=aws` in my .zshrc

### Service configuration (serverless-compose.yml) content

```yaml
N/A
```

### Command name and used flags

serverless deploy

### Command output

```shell
...
Request network error: FetchError: request to https://service-xxxxxx-xxxxxx.gz.apigw.tencentcs.com/release/ failed, reason: write EPROTO xxxxxxxxxxxx:error:xxxxxxxxxx:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1600:SSL alert number 80
```

**Comment by medikoo** [comment]
`SERVERLESS_PLATFORM_VENDOR` is Serverless Components specific settings.

If you're in china, simply set `SLS_GEO_LOCATION=no-cn` and Framework should work as everywhere else.

Nonetheless we indeed need to turn off Tencent support, as it stopped working
