### ISSUE TITLE
Running commands in scope of specific project 

### ISSUE THREAD

**Issue by pgrzesik** [serverless/compose#4]
**Problem**

Some users might want to invoke "standard" Framework commands in scope of their component. If that component depends on other components, we should be able to pass the state to such commands so all variables can be resolved successfully.

**Scenarios**

1. User changes directory to specific `serverless-framework` component project, e.g. `cd api` and tries to run `serverless invoke function --function myfunc`. The `api` component depends on another component that has not been deployed yet.
2. User changes directory to specific `serverless-framework` component project, e.g. `cd api` and tries to run `serverless invoke function --function myfunc`. The `api` component depends on another component that has been previously deployed.

**Questions**

General:
1. Should we allow running commands in this manner if project is using `components`? 
2. How should we detect if given Framework project is a part of `components`-based project?

If we support such an approach:
1. How should we pass state to the component that depends on other components if we run the command in scope of the specific `serverless-framework` component?

**Comment by mnapoli** [comment]
Closing in favor of improving the error message: https://github.com/serverless/compose/issues/29

Solving this properly is a good task, a quality of life improvement is to improve the error message instead.
