### ISSUE TITLE
Introduce way to refresh/repopulate outputs (state) - `slsc outputs:refresh`

### ISSUE THREAD

**Issue by pgrzesik** [serverless/compose#45]
Introduce `outputs:refresh` command that will allow to repopulate/sync outputs (state) locally

**Comment by pgrzesik** [comment]
Hey @mnapoli - I've started the implementation of this and I'm not sold on the command format here - as of right now, we're supporting two formats for service-specific commands and this conflicts with one of them - it's pretty much equivalent to invoking command `refresh` on a service called `outputs`. What do you think about supporting `outputs refresh` or `refresh-outputs` command? 

Or maybe first we should make a decision on how we want to support the service-specific commands?

**Comment by mnapoli** [comment]
Oh 100% good point, this isn't a sub-command of a service and this could create conflicts.

`slsc refresh-outputs` sounds like the safest option as it doesn't force us down the road of using spaces for sub-commands (spaces have the problem of not allowing to distinguish options and arguments, so I think we should try to avoid that ideally).
