### ISSUE TITLE
Handle possible Telemetry race conditions

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#52]
There may be cases where each Serverless Framework subprocess might want to upload stored Telemetry data in parallel, possibly resulting in race conditions.

The goal of this issue is to prevent this from being a problem.

**Comment by pgrzesik** [comment]
This is addressed thanks to the following PRs:
- https://github.com/serverless/serverless/pull/10966
- https://github.com/serverlessinc/platform/commit/b3094f8421421cc0815f7e9f9222fe90aab5e34c
- https://github.com/serverlessinc/event-integrations/pull/85
- https://github.com/serverless/compose/pull/81

We can still experience duplicated events for Framework versions older than `v3.13.0` but I think this is acceptable as `compose` currently is only supported for versions `v3.7.7` and higher, so the risk is relatively small (I expect most people upgrading anyway)
