### ISSUE TITLE
Improve formatting of initialization errors

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#53]
We want to format errors closer to the Serverless Framework formatting.

## Current

<img width="872" alt="image" src="https://user-images.githubusercontent.com/720328/160626832-59968e94-3eb9-475b-a90a-ee4044175f47.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/720328/160626875-ba48b8c7-04d3-4dc9-a5bf-0e16283734a3.png">

## Target

Example of a Serverless Framework init error:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/720328/160627079-e3969bba-4562-4522-a43d-409fdf2760db.png">

we should follow that same approach:

- helpful links in gray at the top
- `Error:` in red on its own line
- hide the stack trace for "user errors"
- show the stack trace for "programmer errors"

Here's what the top block could contain for now:

```
Environment: darwin, node 17.4.0, compose 0.0.8
Docs:        github.com/serverless/compose
Support:     github.com/serverless/compose/issues
```

**Comment by pgrzesik** [comment]
The proposed solution is great, however, we also have different error scenarios - the ones that happen as a part of executing a command for a specific service that fails, the example below:

![41FD85DD-A84F-4010-B2C0-5F1C38983D41](https://user-images.githubusercontent.com/17499590/161047464-6831a097-1b37-44ae-be14-c315fa516788.jpeg)

Do you think we should improve this scenario in some way as well?

**Comment by mnapoli** [comment]
I think for these errors we're _kinda_ good.

Ideally there shouldn't be an "Error:" prefix (to be consistent with other error messages, and keep the dynamic output short). Maybe that's a detail we can improve?
