### ISSUE TITLE
Improve DX for unsupported Framework commands, CLI options and YAML options

### ISSUE THREAD

**Issue by mnapoli** [serverless/compose#62]
Serverless Compose does not support all CLI commands, CLI options and YAML options of Serverless Framework.

To avoid surprising users, we want to catch easy mistakes/confusions and clarify these with great error messages.

- [x] Improve DX for unsupported CLI commands (#61)
- [ ] Improve DX for unsupported CLI options
- [x] Detect common YAML mistakes with nice error messages (more details below) #68 

Regarding YAML mistakes, eventually we should have complex schema validation, but in the meantime we could start with this: detect the following root properties and throw a nice error message:

```yaml
service:
provider:
functions:
params:
frameworkVersion:
useDotenv:
package:
layers:
resources:
```

The error message could be:

> Invalid property "${property}" in serverless-compose.yml.
> This property is supported in Serverless Framework (serverless.yml), but not in serverless-compose.yml.
> You can search and/or open feature requests here: https://github.com/serverless/compose

If this is any other invalid root property (e.g. `foo:`), the message could simply be:

> Invalid property "${property}" in serverless-compose.yml.

Side-note regarding mentioning "serverless-compose.yml" in error messages: I think it would be great if we could name it that way, it's super clear for users (unlike saying "Service configuration" like in Serverless Framework). However to be exact and reliable, that means we should dynamically populate that name once we have support for #56

**Comment by mnapoli** [comment]
For all commands and CLI options we could go the route of defining CLI command schemas, and validating. @pgrzesik is that too early to invest it this? (I don't know how much effort this is, because I guess we want to reuse or copy the behavior from SF)

**Comment by pgrzesik** [comment]
Hey, sorry for not responding sooner, I've missed the notification. I think we can skip it temporarily because ideally it should be implemented as a part of the logic that we already have in the Framework Core. We can still come back to it and implement it before integrating with Framework directly if we will really need it.

**Comment by pgrzesik** [comment]
That's a great suggestion @mnapoli 👍
